# Generated by Django 5.0.3 on 2024-04-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="body",
            field=models.TextField(blank=True, default="", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="title",
            field=models.CharField(blank=True, default="", max_length=20, null=True),
        ),
    ]
